require('dotenv').config();
const Discord = require('discord.js');
const client = new Discord.Client();

let complements = [
    'LOVE YOURSELF, YOU WONDERFUL FUCKING BIG WORM!',
    'EVERYONE HERE LOVES YOU, YOU BEAUTIFUL BEAUTIFUL SLINKY!',
    'YOU ARE BEAUTIFUL, YOU FUCKING WIZARD BITCH!',
    'YOUR PRESENCE IS A LIGHT IN EVERYONE\'S LIFE SO LOVE YOURSELF YOU GOOD NOODLE!',
    'YOU ARE WORTH MORE TO US THAN YOU COULD EVER IMAGINE YOU SWEET, KIND, CARING, WONDERFUL BEAN!',
    'DON\'T BE MEAN TO YOURSELF! YOU DESERVE KINDNESS, YOU AMAZING FRIEND!',
    'IT\'S OK TO BE SAD BUT IT IS NOT OK TO BE MEAN TO A BEAUTIFUL BABY RODENT LIKE YOURSELF!',
    'YOU ARE POGGERS!',
    'THANK YOU FOR BEING A WONDERFUL FRIEND AND AN EVEN BETTER PERSON!',
    'YOU ARE AMAZING AND LOVED AND BEAUTIFUL AND KIND AND DESERVING OF KINDESS!',
    'YOU ARE DESERVING OF LOVE AND HAPPINESS!',
    'YOU CAN\'T SPELL HAPPINESS WITHOUT PENIS AND YOU PUT PENIS IN MY LIFE!',
    'EVERYONE HERE WANTS THE BEST FOR YOU AND THINKS YOU DESERVE TO BE HAPPY!',
];

client.on('message', message=>{
    if(message.content.toLowerCase() === 'r@t')
        message.channel.send(complements[Math.floor(Math.random() * complements.length)]);
});

client.login(process.env.TOKEN)
